apiVersion: v1
kind: ConfigMap
metadata:
  name: nagp-devops-us-develop-config
  namespace: kubernetes-cluster-gopalkumar
  labels:
    app: nagp-devops-us-develop
data:
  BASE_URL: "https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/"
  ENVIRONMENT: "Development"