apiVersion: v1
kind: ConfigMap
metadata:
  name: nagp-devops-us-master-config
  namespace: kubernetes-cluster-gopalkumar
  labels:
    app: nagp-devops-us-master
data:
  BASE_URL: "https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/"
  ENVIRONMENT: "Production"