apiVersion: v1
kind: Service
metadata:
  name: nagp-devops-us-lb-service
  namespace: kubernetes-cluster-gopalkumar
spec:
  selector:
    app: nagp-devops-us
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
  type: LoadBalancer